version: "3.8"

services:
  api:
    build: back-end/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    restart: always
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - $PWD/db_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  front:
    build: front-end/
    ports:
      - 3000:3000
    restart: always